# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	# Custom vars
	hosts = ['vagrant.localhost1.com', 'vagrant.localhost2.com']
	vagrant_home_folder = "/home/vagrant/vagrant_data"

	config.vm.box = "ubuntu/xenial64"

	config.vm.network "private_network", ip: "192.168.33.10" ## remember to make the ip unique
	config.vm.hostname = "testbox"
	config.vm.synced_folder "vagrant_data/", vagrant_home_folder


	if Vagrant.has_plugin?('vagrant-hostsupdater')
		config.hostsupdater.aliases = hosts
		config.hostsupdater.remove_on_suspend = false		
	end

	# Prevent TTY Errors (copied from laravel/homestead: "homestead.rb" file)... By default this is "bash -l".
	# https://superuser.com/a/1182104
	config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
	
	config.vm.provision :shell, :path => 'setup/provision.sh', :args => "#{vagrant_home_folder}"

	hosts.each do |host|
		config.vm.provision :shell, :path => 'setup/setup-virtualhost.sh', :args => "#{host}", run: "always"
	end

	

end
